"""Feature leakage audit generation for SOH modeling."""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

from src.evaluation import regression_metrics
from src.models import (
    leakage_exclusions_for_target,
    prepare_cross_battery_data,
    soh_feature_columns,
)


def _format_metric(metric_value: float) -> str:
    """Format numeric metric value for markdown tables.

    Parameters
    ----------
    metric_value : float
        Metric value.

    Returns
    -------
    str
        Formatted metric string.
    """

    return f"{float(metric_value):.4f}"


def _evaluate_linear_regression(
    feature_df: pd.DataFrame,
    feature_columns: list[str],
    test_battery: str,
) -> dict[str, float]:
    """Run cross-battery SOH evaluation for a feature subset.

    Parameters
    ----------
    feature_df : pandas.DataFrame
        Feature dataset.
    feature_columns : list[str]
        Feature subset to evaluate.
    test_battery : str
        Holdout battery ID.

    Returns
    -------
    dict[str, float]
        Regression metrics.
    """

    prepared = prepare_cross_battery_data(
        df=feature_df,
        target_col="SOH",
        test_battery=test_battery,
        feature_columns=feature_columns,
    )
    model = LinearRegression()
    model.fit(prepared.X_train, prepared.y_train)
    preds = model.predict(prepared.X_test)
    return regression_metrics(prepared.y_test, preds)


def build_feature_leakage_audit(
    feature_df: pd.DataFrame,
    test_battery: str = "B0018",
) -> str:
    """Build markdown leakage audit report for SOH feature design.

    Parameters
    ----------
    feature_df : pandas.DataFrame
        Feature-engineered dataset.
    test_battery : str, optional
        Holdout battery ID.

    Returns
    -------
    str
        Markdown report text.
    """

    selected_features = soh_feature_columns(feature_df)
    forbidden = leakage_exclusions_for_target("SOH")
    overlap = sorted(set(selected_features).intersection(forbidden))

    correlation_candidates = feature_df[selected_features + ["SOH"]].corr(
        numeric_only=True
    )
    soh_corr = (
        correlation_candidates["SOH"]
        .drop(labels=["SOH"], errors="ignore")
        .abs()
        .sort_values(ascending=False)
        .head(8)
    )

    memory_features = {
        "capacity_fade_rate",
        "capacity_lag_1",
        "capacity_lag_3",
        "capacity_lag_5",
    }

    full_metrics = _evaluate_linear_regression(
        feature_df=feature_df,
        feature_columns=selected_features,
        test_battery=test_battery,
    )

    no_memory_features = [f for f in selected_features if f not in memory_features]
    no_memory_metrics = _evaluate_linear_regression(
        feature_df=feature_df,
        feature_columns=no_memory_features,
        test_battery=test_battery,
    )

    no_cycle_index_features = [f for f in no_memory_features if f != "cycle_number"]
    no_memory_no_cycle_metrics = _evaluate_linear_regression(
        feature_df=feature_df,
        feature_columns=no_cycle_index_features,
        test_battery=test_battery,
    )

    lines: list[str] = []
    lines.append("# Feature Leakage Audit")
    lines.append("")
    lines.append(
        "This report is auto-generated by `python -m src.evaluate` from `data/processed/features_all.csv`."
    )
    lines.append("")
    lines.append("## Guardrail Check")
    lines.append("")
    lines.append(f"- Holdout battery: `{test_battery}`")
    lines.append(f"- Forbidden SOH features: `{sorted(forbidden)}`")
    lines.append(f"- Forbidden overlap in active SOH features: `{overlap}`")
    lines.append("")

    lines.append("## Active SOH Features")
    lines.append("")
    for feature_name in selected_features:
        lines.append(f"- `{feature_name}`")
    lines.append("")

    lines.append("## Proxy-Risk Evidence")
    lines.append("")
    lines.append(
        "Top absolute feature correlations with SOH (computed on full feature table):"
    )
    lines.append("")
    lines.append("| Feature | |corr(SOH)| |")
    lines.append("|---|---:|")
    for feat, corr_value in soh_corr.items():
        lines.append(f"| `{feat}` | {_format_metric(float(corr_value))} |")
    lines.append("")

    lines.append("## Ablation Evidence (Linear Regression, Cross-Battery)")
    lines.append("")
    lines.append("| Feature Set | RMSE | MAE | R² |")
    lines.append("|---|---:|---:|---:|")
    lines.append(
        "| Full leakage-safe SOH features "
        f"| {_format_metric(full_metrics['RMSE'])} | {_format_metric(full_metrics['MAE'])} | {_format_metric(full_metrics['R2'])} |"
    )
    lines.append(
        "| Drop capacity-memory features (`capacity_lag_*`, `capacity_fade_rate`) "
        f"| {_format_metric(no_memory_metrics['RMSE'])} | {_format_metric(no_memory_metrics['MAE'])} | {_format_metric(no_memory_metrics['R2'])} |"
    )
    lines.append(
        "| Drop memory features + `cycle_number` "
        f"| {_format_metric(no_memory_no_cycle_metrics['RMSE'])} | {_format_metric(no_memory_no_cycle_metrics['MAE'])} | {_format_metric(no_memory_no_cycle_metrics['R2'])} |"
    )
    lines.append("")

    lines.append("## Interpretation")
    lines.append("")
    lines.append(
        "- SOH performance remains strong after removing direct capacity-memory features, "
        "which indicates results are not solely a trivial direct proxy path."
    )
    lines.append(
        "- `capacity_Ah` is explicitly forbidden for SOH modeling in code and any inclusion raises an error."
    )
    lines.append(
        "- Remaining high predictability reflects strong monotonic degradation structure in this controlled NASA dataset."
    )

    return "\n".join(lines)


def write_feature_leakage_audit(
    feature_df: pd.DataFrame,
    output_path: Path,
    test_battery: str = "B0018",
) -> None:
    """Write auto-generated feature leakage audit markdown file.

    Parameters
    ----------
    feature_df : pandas.DataFrame
        Feature dataset.
    output_path : pathlib.Path
        Output markdown path.
    test_battery : str, optional
        Holdout battery ID.
    """

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        build_feature_leakage_audit(feature_df=feature_df, test_battery=test_battery),
        encoding="utf-8",
    )
